class_name NCONSTANTS

enum {  CFI_TIMESTAMP 		= -1, 
		CFI_TIMESTAMPPREV 	= -2,
		
		CFI_PLAYER_NODENAME	= -3,
		CFI_TIMESTAMP_F0 	= -4,
		CFI_TIMESTAMP_RECIEVED = -5, 
		CFI_ARRIVALDELAY = -6, 
		CFI_NOTHINFRAME = -8, 
		
		CFI_ZERO = 0,
		
		CFI_VISIBLE = 9,
		CFI_RECT_POSITION = 10,
		CFI_FIRE_KEY = 30
	}
