class_name NCONSTANTS

enum {  CFI_TIMESTAMP 		= -1, 
		CFI_TIMESTAMPPREV 	= -2,
		
		CFI_PLAYER_NODENAME	= -3,
		CFI_TIMESTAMP_RECIEVED = -5, 
		CFI_ARRIVALDELAY = -6, 
		
		CFI_ZERO = 0,
		
		CFI_ANIMTRACKS = 10000
	}
